services:
  - type: web
    name: lukia-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:create_app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FRONTEND_URL
        value: https://lukia-frontend-krwj.onrender.com  # Replace with your actual frontend URL

  - type: web
    name: lukia-frontend
    env: static
    buildCommand: cd lukia-frontend && npm install && npm run build
    staticPublishPath: ./lukia-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://lukia-backend-krwj.onrender.com